"""driver_drafts pivot + DF codes

Adds a pivot/audit table to track driver drafts with stable draft_id codes in
format DF-NNN generated by a DB sequence.

Revision ID: 0029_driver_drafts
Revises: 0028_violation_proofs
Create Date: 2026-03-26
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# IMPORTANT: alembic_version.version_num is VARCHAR(32) in this project.
# Keep revision ids <= 32 chars to avoid truncation errors.
revision = "0029_driver_drafts"
down_revision = "0028_violation_proofs"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Draft codes: DF-001, DF-002, ... (continues DF-1000+)
    op.execute("CREATE SEQUENCE IF NOT EXISTS draft_code_seq START WITH 1 INCREMENT BY 1")

    op.create_table(
        "driver_drafts",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True, nullable=False),
        sa.Column(
            "driver_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("drivers.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "draft_id",
            sa.String(length=20),
            nullable=False,
            unique=True,
            server_default=sa.text("'DF-' || lpad(nextval('draft_code_seq')::text, 3, '0')"),
        ),
        sa.Column(
            "created_by",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.UniqueConstraint("driver_id", name="uq_driver_drafts_driver_id"),
    )
    op.create_index("idx_driver_drafts_driver_id", "driver_drafts", ["driver_id"])
    op.create_index("idx_driver_drafts_draft_id", "driver_drafts", ["draft_id"])
    op.create_index("idx_driver_drafts_created_by", "driver_drafts", ["created_by"])


def downgrade() -> None:
    op.drop_index("idx_driver_drafts_created_by", table_name="driver_drafts")
    op.drop_index("idx_driver_drafts_draft_id", table_name="driver_drafts")
    op.drop_index("idx_driver_drafts_driver_id", table_name="driver_drafts")
    op.drop_table("driver_drafts")
    op.execute("DROP SEQUENCE IF EXISTS draft_code_seq")

