"""draft updates on vehicle related models

Revision ID: 0033_vehicle_drafts
Revises: 0032_merge_org_driver_heads
Create Date: 2026-03-27 20:43:15.629401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0033_vehicle_drafts'
down_revision: Union[str, None] = '0032_merge_org_driver_heads'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(sa.schema.CreateSequence(sa.Sequence("draft_number_seq")))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_drafts',
    sa.Column('draft_number', sa.String(length=20), server_default=sa.text("'DR-' || lpad(nextval('draft_number_seq')::text, 3, '0')"), nullable=False),
    sa.Column('vehicle_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_by_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_drafts_draft_number'), 'vehicle_drafts', ['draft_number'], unique=True)
    op.create_index(op.f('ix_vehicle_drafts_vehicle_id'), 'vehicle_drafts', ['vehicle_id'], unique=True)
    op.add_column('vehicles', sa.Column('availability', sa.Enum('ACTIVE', 'UNAVAILABLE', 'IN_MAINTENANCE', name='vehicleavailability', native_enum=False), server_default='ACTIVE', nullable=False))
    op.alter_column('vehicles', 'registration_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('vehicles', 'current_mileage',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # status was VARCHAR(14) with values like DECOMMISSIONED / IN_MAINTENANCE / UNAVAILABLE.
    # App model keeps lifecycle in status (DRAFT | ACTIVE) and operational state in availability.
    op.execute(
        sa.text(
            """
            UPDATE vehicles
            SET availability = 'UNAVAILABLE', status = 'ACTIVE'
            WHERE status IN ('DECOMMISSIONED', 'UNAVAILABLE')
            """
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE vehicles
            SET availability = 'IN_MAINTENANCE', status = 'ACTIVE'
            WHERE status = 'IN_MAINTENANCE'
            """
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE vehicles
            SET status = 'ACTIVE'
            WHERE status NOT IN ('DRAFT', 'ACTIVE')
            """
        )
    )
    op.alter_column('vehicles', 'status',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('DRAFT', 'ACTIVE', name='vehiclestatus', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_vehicles_availability'), 'vehicles', ['availability'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_availability'), table_name='vehicles')
    op.alter_column('vehicles', 'status',
               existing_type=sa.Enum('DRAFT', 'ACTIVE', name='vehiclestatus', native_enum=False),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)
    op.alter_column('vehicles', 'current_mileage',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('vehicles', 'registration_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('vehicles', 'availability')
    op.drop_index(op.f('ix_vehicle_drafts_vehicle_id'), table_name='vehicle_drafts')
    op.drop_index(op.f('ix_vehicle_drafts_draft_number'), table_name='vehicle_drafts')
    op.drop_table('vehicle_drafts')
    op.execute(sa.schema.DropSequence(sa.Sequence("draft_number_seq")))

    # ### end Alembic commands ###
