"""creating nullable vehicle fields

Revision ID: 0034_nullable_vehicle_fields
Revises: 0033_vehicle_drafts
Create Date: 2026-03-27 21:54:20.695625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0034_nullable_vehicle_fields'
down_revision: Union[str, None] = '0033_vehicle_drafts'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'vehicle_type',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('vehicles', 'fuel_type',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'fuel_type',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.alter_column('vehicles', 'vehicle_type',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    # ### end Alembic commands ###
