"""Add route codes + route telematics events.

Adds:
- routes.route_code (RT-NNN) generated by route_code_seq
- routes.estimated_drive_time_min / routes.actual_drive_time_min
- route_events table for telematics/safety events
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# IMPORTANT: alembic_version.version_num is VARCHAR(32) in this project.
# Keep revision ids <= 32 chars to avoid truncation errors.
revision: str = "0038_route_events_and_route_code"
down_revision: str | None = "0037_draft_submit_marker"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # Route code sequence (RT-NNN).
    op.execute("CREATE SEQUENCE IF NOT EXISTS route_code_seq START WITH 1 INCREMENT BY 1")

    op.add_column(
        "routes",
        sa.Column(
            "route_code",
            sa.String(length=20),
            nullable=False,
            server_default=sa.text("'RT-' || lpad(nextval('route_code_seq')::text, 3, '0')"),
        ),
    )
    op.add_column(
        "routes",
        sa.Column(
            "route_type",
            sa.String(length=20),
            nullable=False,
            server_default=sa.text("'DELIVERY'"),
        ),
    )

    op.add_column("routes", sa.Column("estimated_drive_time_min", sa.Float(), nullable=True))
    op.add_column("routes", sa.Column("actual_drive_time_min", sa.Float(), nullable=True))

    # Optional backfill: initialize estimates/actuals from existing total_duration_min.
    op.execute(
        """
        UPDATE routes
        SET estimated_drive_time_min = total_duration_min,
            actual_drive_time_min = total_duration_min
        WHERE total_duration_min IS NOT NULL
        """
    )

    op.create_unique_constraint("uq_routes_route_code", "routes", ["route_code"])
    op.create_index("ix_routes_route_code", "routes", ["route_code"])
    op.create_index("ix_routes_route_type", "routes", ["route_type"])

    # Telemetics / safety events table.
    op.create_table(
        "route_events",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=False),
            primary_key=True,
            nullable=False,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "route_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("routes.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "driver_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("drivers.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lng", sa.Float(), nullable=True),
        sa.Column(
            "event_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
    )

    op.execute("CREATE INDEX ix_route_events_route_id_occurred_at ON route_events (route_id, occurred_at DESC)")
    op.execute("CREATE INDEX ix_route_events_driver_id_occurred_at ON route_events (driver_id, occurred_at DESC)")
    op.execute("CREATE INDEX ix_route_events_event_type_occurred_at ON route_events (event_type, occurred_at DESC)")


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_route_events_route_id_occurred_at")
    op.execute("DROP INDEX IF EXISTS ix_route_events_driver_id_occurred_at")
    op.execute("DROP INDEX IF EXISTS ix_route_events_event_type_occurred_at")
    op.drop_table("route_events")

    op.drop_index("ix_routes_route_type", table_name="routes")
    op.drop_index("ix_routes_route_code", table_name="routes")
    op.drop_constraint("uq_routes_route_code", "routes", type_="unique")

    op.drop_column("routes", "actual_drive_time_min")
    op.drop_column("routes", "estimated_drive_time_min")
    op.drop_column("routes", "route_type")
    op.drop_column("routes", "route_code")

    op.execute("DROP SEQUENCE IF EXISTS route_code_seq")

