"""add organization_id to audit_log

Revision ID: 0058_add_audit_org
Revises: 0057_admin_ref
Create Date: 2026-03-26 23:35:02.158887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0058_add_audit_org'
down_revision: Union[str, None] = '0057_admin_ref'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_tiers',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('available_for', sa.Enum('B2B', 'B2C', 'BOTH', name='clientavailability', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='pricingtierstatus', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # NOTE: The credit_notes table is already created in an earlier migration (72bf17bcac4c).
    # The duplicate creation and its indexes have been removed to avoid conflicts.

    # NOTE: invoice_credit_applications, invoice_events, and invoice_pdf_artifacts
    # are already created in migration 72bf17bcac4c. Duplicate blocks removed.
    op.add_column('audit_log', sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_index(op.f('ix_audit_log_organization_id'), 'audit_log', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'audit_log', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    # op.drop_column('drivers', 'first_name')
    # op.drop_column('drivers', 'email')
    # op.drop_column('drivers', 'phone')
    # op.drop_column('drivers', 'last_name')
    # op.add_column('invoices', sa.Column('payment_status', sa.String(length=20), nullable=False))
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    # op.create_index(op.f('ix_invoices_payment_status'), 'invoices', ['payment_status'], unique=False)
    op.alter_column('org_contacts', 'contact_role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ACCOUNT_OWNER', 'BILLING', 'OPERATIONS', 'TECHNICAL', 'OTHER', name='contactrole', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'ACCOUNT_OWNER'::character varying"))
    op.alter_column('org_contacts', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'ACTIVE', 'INACTIVE', name='contactstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.drop_constraint(op.f('org_credit_configs_organization_id_key'), 'org_credit_configs', type_='unique')
    op.drop_index(op.f('ix_org_credit_configs_organization_id'), table_name='org_credit_configs')
    op.create_index(op.f('ix_org_credit_configs_organization_id'), 'org_credit_configs', ['organization_id'], unique=True)
    op.drop_constraint(op.f('uq_org_discount_configs_org_id'), 'org_discount_configs', type_='unique')
    op.drop_index(op.f('ix_org_discount_configs_organization_id'), table_name='org_discount_configs')
    op.create_index(op.f('ix_org_discount_configs_organization_id'), 'org_discount_configs', ['organization_id'], unique=True)
    op.drop_index(op.f('ix_org_notes_org_active'), table_name='org_notes', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('org_payment_configs', 'payment_model',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('CARD', 'BANK_TRANSFER', 'CREDIT_ACCOUNT', name='paymentmodel', native_enum=False),
               existing_nullable=False)
    op.alter_column('org_payment_configs', 'billing_schedule',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('IMMEDIATE', 'FIXED_MONTHLY_DATE', 'DAYS_AFTER_ORDER', name='billingschedule', native_enum=False),
               existing_nullable=False)
    op.alter_column('org_payment_configs', 'vat_rate',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('STANDARD_20', 'REDUCED_5', 'ZERO_RATED', 'EXEMPT', name='vatrate', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'STANDARD_20'::character varying"))
    op.alter_column('org_payment_configs', 'vat_treatment',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('UK', 'OVERSEAS', name='vattreatment', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'UK'::character varying"))
    op.drop_constraint(op.f('org_payment_configs_organization_id_key'), 'org_payment_configs', type_='unique')
    op.drop_index(op.f('ix_org_payment_configs_organization_id'), table_name='org_payment_configs')
    op.create_index(op.f('ix_org_payment_configs_organization_id'), 'org_payment_configs', ['organization_id'], unique=True)
    op.drop_constraint(op.f('org_suspension_configs_organization_id_key'), 'org_suspension_configs', type_='unique')
    op.drop_index(op.f('ix_org_suspension_configs_organization_id'), table_name='org_suspension_configs')
    op.create_index(op.f('ix_org_suspension_configs_organization_id'), 'org_suspension_configs', ['organization_id'], unique=True)
    op.alter_column('organizations', 'industry',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ECOMMERCE', 'HOME_LIFESTYLE', 'RETAIL', 'WHOLESALE_DISTRIBUTION', 'HEALTHCARE_PHARMA', 'TECHNOLOGY_SOFTWARE', 'MANUFACTURING', 'LOGISTICS_TRANSPORT', 'CONSTRUCTION', 'FOOD_BEVERAGE', 'FINANCE_INSURANCE', 'EDUCATION', 'MEDIA_ENTERTAINMENT', 'OTHER', name='industrytype', native_enum=False),
               existing_nullable=False)
    op.alter_column('organizations', 'company_size',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('EMPLOYEES_1_10', 'EMPLOYEES_11_50', 'EMPLOYEES_51_200', 'EMPLOYEES_201_500', 'EMPLOYEES_501_1000', 'EMPLOYEES_1000_PLUS', name='companysize', native_enum=False),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_organizations_reference'), 'organizations', type_='unique')
    op.drop_index(op.f('ix_organizations_reference'), table_name='organizations')
    op.create_index(op.f('ix_organizations_reference'), 'organizations', ['reference'], unique=True)
    op.alter_column('service_tier', 'status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('ACTIVE', 'INACTIVE', name='servicetierstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.create_foreign_key(None, 'suspension_activity', 'suspension_rule', ['rule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('suspension_activity_rule_id_fkey', 'suspension_activity', type_='foreignkey')
    op.alter_column('service_tier', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', name='servicetierstatus', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.drop_index(op.f('ix_organizations_reference'), table_name='organizations')
    op.create_index(op.f('ix_organizations_reference'), 'organizations', ['reference'], unique=False)
    op.create_unique_constraint(op.f('uq_organizations_reference'), 'organizations', ['reference'], postgresql_nulls_not_distinct=False)
    op.alter_column('organizations', 'company_size',
               existing_type=sa.Enum('EMPLOYEES_1_10', 'EMPLOYEES_11_50', 'EMPLOYEES_51_200', 'EMPLOYEES_201_500', 'EMPLOYEES_501_1000', 'EMPLOYEES_1000_PLUS', name='companysize', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('organizations', 'industry',
               existing_type=sa.Enum('ECOMMERCE', 'HOME_LIFESTYLE', 'RETAIL', 'WHOLESALE_DISTRIBUTION', 'HEALTHCARE_PHARMA', 'TECHNOLOGY_SOFTWARE', 'MANUFACTURING', 'LOGISTICS_TRANSPORT', 'CONSTRUCTION', 'FOOD_BEVERAGE', 'FINANCE_INSURANCE', 'EDUCATION', 'MEDIA_ENTERTAINMENT', 'OTHER', name='industrytype', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_org_suspension_configs_organization_id'), table_name='org_suspension_configs')
    op.create_index(op.f('ix_org_suspension_configs_organization_id'), 'org_suspension_configs', ['organization_id'], unique=False)
    op.create_unique_constraint(op.f('org_suspension_configs_organization_id_key'), 'org_suspension_configs', ['organization_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_org_payment_configs_organization_id'), table_name='org_payment_configs')
    op.create_index(op.f('ix_org_payment_configs_organization_id'), 'org_payment_configs', ['organization_id'], unique=False)
    op.create_unique_constraint(op.f('org_payment_configs_organization_id_key'), 'org_payment_configs', ['organization_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('org_payment_configs', 'vat_treatment',
               existing_type=sa.Enum('UK', 'OVERSEAS', name='vattreatment', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'UK'::character varying"))
    op.alter_column('org_payment_configs', 'vat_rate',
               existing_type=sa.Enum('STANDARD_20', 'REDUCED_5', 'ZERO_RATED', 'EXEMPT', name='vatrate', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'STANDARD_20'::character varying"))
    op.alter_column('org_payment_configs', 'billing_schedule',
               existing_type=sa.Enum('IMMEDIATE', 'FIXED_MONTHLY_DATE', 'DAYS_AFTER_ORDER', name='billingschedule', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('org_payment_configs', 'payment_model',
               existing_type=sa.Enum('CARD', 'BANK_TRANSFER', 'CREDIT_ACCOUNT', name='paymentmodel', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.create_index(op.f('ix_org_notes_org_active'), 'org_notes', ['organization_id', 'is_pinned', 'created_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('ix_org_discount_configs_organization_id'), table_name='org_discount_configs')
    op.create_index(op.f('ix_org_discount_configs_organization_id'), 'org_discount_configs', ['organization_id'], unique=False)
    op.create_unique_constraint(op.f('uq_org_discount_configs_org_id'), 'org_discount_configs', ['organization_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_org_credit_configs_organization_id'), table_name='org_credit_configs')
    op.create_index(op.f('ix_org_credit_configs_organization_id'), 'org_credit_configs', ['organization_id'], unique=False)
    op.create_unique_constraint(op.f('org_credit_configs_organization_id_key'), 'org_credit_configs', ['organization_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('org_contacts', 'status',
               existing_type=sa.Enum('PENDING', 'ACTIVE', 'INACTIVE', name='contactstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('org_contacts', 'contact_role',
               existing_type=sa.Enum('ACCOUNT_OWNER', 'BILLING', 'OPERATIONS', 'TECHNICAL', 'OTHER', name='contactrole', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'ACCOUNT_OWNER'::character varying"))
    # op.drop_index(op.f('ix_invoices_payment_status'), table_name='invoices')
    op.alter_column('invoices', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # op.drop_column('invoices', 'payment_status')
    # op.add_column('drivers', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # op.add_column('drivers', sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # op.add_column('drivers', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # op.add_column('drivers', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # op.drop_constraint(None, 'audit_log', type_='foreignkey')
    op.drop_index(op.f('ix_audit_log_organization_id'), table_name='audit_log')
    op.drop_column('audit_log', 'organization_id')
    # NOTE: invoice_credit_applications, invoice_events, and invoice_pdf_artifacts
    # are managed by migration 72bf17bcac4c. Duplicate drops/re-creation removed.
    op.drop_table('pricing_tiers')
    # NOTE: credit_notes table drop removed – it is managed by the earlier migration.

    # ### end Alembic commands ###
