"""add severity to audit_log

Revision ID: 0059_add_severity
Revises: 0058_add_audit_org
Create Date: 2026-03-27 01:08:51.265246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0059_add_severity'
down_revision: Union[str, None] = '0058_add_audit_org'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('severity', sa.String(length=20), server_default='INFO', nullable=False))
    op.create_index(op.f('ix_audit_log_severity'), 'audit_log', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_severity'), table_name='audit_log')
    op.drop_column('audit_log', 'severity')
    # ### end Alembic commands ###
