"""add_audit_category_column_nullable

Revision ID: 0060_add_category
Revises: 0059_add_severity
Create Date: 2026-03-27 21:13:17.464096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0060_add_category'
down_revision: Union[str, None] = '0059_add_severity'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('category', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_audit_log_category'), 'audit_log', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_category'), table_name='audit_log')
    op.drop_column('audit_log', 'category')
    # ### end Alembic commands ###
