"""add_audit_event_type_column

Revision ID: 0061_add_event_type
Revises: 0060_add_category
Create Date: 2026-03-27 21:27:35.791165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0061_add_event_type'
down_revision: Union[str, None] = '0060_add_category'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('event_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_audit_log_event_type'), 'audit_log', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_event_type'), table_name='audit_log')
    op.drop_column('audit_log', 'event_type')
    # ### end Alembic commands ###
