"""add_audit_extra_fields

Revision ID: 0062_add_extra
Revises: 0061_add_event_type
Create Date: 2026-03-28 01:30:27.636121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0062_add_extra'
down_revision: Union[str, None] = '0061_add_event_type'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('browser', sa.String(length=50), nullable=True))
    op.add_column('audit_log', sa.Column('device', sa.String(length=100), nullable=True))
    op.add_column('audit_log', sa.Column('os', sa.String(length=50), nullable=True))
    op.add_column('audit_log', sa.Column('audit_ref', sa.String(length=50), nullable=True))
    op.add_column('audit_log', sa.Column('entity_ref', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_audit_log_audit_ref'), 'audit_log', ['audit_ref'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_ref'), 'audit_log', ['entity_ref'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_entity_ref'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_audit_ref'), table_name='audit_log')
    op.drop_column('audit_log', 'entity_ref')
    op.drop_column('audit_log', 'audit_ref')
    op.drop_column('audit_log', 'os')
    op.drop_column('audit_log', 'device')
    op.drop_column('audit_log', 'browser')
    # ### end Alembic commands ###
