"""add audit saved views

Revision ID: 0063_add_saved_views
Revises: 0062_add_extra
Create Date: 2026-04-03 01:34:31.014183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0063_add_saved_views'
down_revision: Union[str, None] = '0062_add_extra'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_saved_views',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_saved_views_organization_id'), 'audit_saved_views', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_saved_views_user_id'), 'audit_saved_views', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_saved_views_user_id'), table_name='audit_saved_views')
    op.drop_index(op.f('ix_audit_saved_views_organization_id'), table_name='audit_saved_views')
    op.drop_table('audit_saved_views')
    # ### end Alembic commands ###
