"""make_audit_saved_views_user_centric

Revision ID: 0064_user_centric_views
Revises: 0063_add_saved_views
Create Date: 2026-04-03 20:15:13.969840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0064_user_centric_views'
down_revision: Union[str, None] = '0063_add_saved_views'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_saved_views', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    # op.drop_index(op.f('ix_org_note_mentions_note_id'), table_name='org_note_mentions')
    # op.drop_index(op.f('ix_org_tag_org_links_org_id'), table_name='org_tag_org_links')
    # op.drop_index(op.f('ix_refresh_tokens_access_jti'), table_name='refresh_tokens')
    # op.drop_index(op.f('ix_sessions_revoked'), table_name='sessions')
    # op.drop_index(op.f('ix_sessions_session_id_revoked'), table_name='sessions')
    # op.drop_index(op.f('ix_sessions_user_id_revoked_last_seen_at'), table_name='sessions')
    op.alter_column('users', 'title',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('MR', 'MRS', 'MS', 'DR', 'PROF', name='usertitle', native_enum=False),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'title',
               existing_type=sa.Enum('MR', 'MRS', 'MS', 'DR', 'PROF', name='usertitle', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # op.create_index(op.f('ix_sessions_user_id_revoked_last_seen_at'), 'sessions', ['user_id', 'revoked', 'last_seen_at'], unique=False)
    op.alter_column('audit_saved_views', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
