"""add notes to driver_time_off and update leave type enum to include all enums

Revision ID: 0309ba573191
Revises: f4670f5faf8d
Create Date: 2026-03-11 13:00:38.278179

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0309ba573191"
down_revision: str | None = "f4670f5faf8d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("driver_time_off", sa.Column("notes", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("driver_time_off", "notes")
    # ### end Alembic commands ###
