"""updated vehicle module related models

Revision ID: 42e057ee7632
Revises: 6698f60b0823
Create Date: 2026-03-12 20:43:39.928344

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "42e057ee7632"
down_revision: str | None = "6698f60b0823"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicle_defects",
        sa.Column("vehicle_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("route_id", sa.String(length=50), nullable=True),
        sa.Column("reported_by_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("reported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("defect_type", sa.Enum("INTERNAL", "EXTERNAL", name="vehicletype", native_enum=False), server_default="INTERNAL", nullable=False),
        sa.Column("category", sa.Enum("ROUTINE_SERVICE", "TYRES", "PART_REPLACEMENT", "BREAKDOWN", name="defectcategory", native_enum=False), nullable=False),
        sa.Column("severity", sa.Enum("CRITICAL", "MAJOR", "MINOR", name="defectseverity", native_enum=False), nullable=False),
        sa.Column("status", sa.Enum("PENDING", "IN_PROGRESS", "RESOLVED", name="defectstatus", native_enum=False), server_default="PENDING", nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("allowed_to_drive", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["reported_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vehicle_defects_route_id"), "vehicle_defects", ["route_id"], unique=False)
    op.create_index(op.f("ix_vehicle_defects_vehicle_id"), "vehicle_defects", ["vehicle_id"], unique=False)
    op.create_table(
        "vehicle_documents",
        sa.Column("vehicle_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("document_type", sa.Enum("MOT", "TAX", "INSURANCE", "OTHER", name="documenttype", native_enum=False), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("policy_number", sa.String(length=100), nullable=True),
        sa.Column("provider", sa.String(length=200), nullable=True),
        sa.Column("uploaded_by_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["uploaded_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_vehicle_documents_vehicle_id_created_at", "vehicle_documents", ["vehicle_id", "created_at"], unique=False)
    op.create_table(
        "vehicle_images",
        sa.Column("vehicle_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("uploaded_by_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(["uploaded_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vehicle_images_vehicle_id"), "vehicle_images", ["vehicle_id"], unique=False)
    op.create_table(
        "vehicle_maintenance_records",
        sa.Column("vehicle_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("maintenance_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("provider_type", sa.Enum("INTERNAL", "EXTERNAL", name="maintenanceprovidertype", native_enum=False), server_default="EXTERNAL", nullable=False),
        sa.Column("date_from", sa.Date(), nullable=False),
        sa.Column("date_to", sa.Date(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("recorded_by_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["recorded_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_vehicle_maintenance_records_vehicle_id_created_at", "vehicle_maintenance_records", ["vehicle_id", "created_at"], unique=False)
    op.create_table(
        "vehicle_schedule_entries",
        sa.Column("vehicle_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("date_from", sa.Date(), nullable=False),
        sa.Column("date_to", sa.Date(), nullable=True),
        sa.Column("type", sa.Enum("OUT_FOR_DELIVERY", "COMPLETED", "MAINTENANCE", "UNAVAILABLE", "AVAILABLE", name="scheduleeventtype", native_enum=False), nullable=False),
        sa.Column("source", sa.Enum("MAINTENANCE", "AVAILABILITY", "ROUTE", name="scheduleentrysource", native_enum=False), nullable=False),
        sa.Column("source_id", sa.String(length=100), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vehicle_schedule_entries_date_from"), "vehicle_schedule_entries", ["date_from"], unique=False)
    op.create_index(op.f("ix_vehicle_schedule_entries_type"), "vehicle_schedule_entries", ["type"], unique=False)
    op.create_index(op.f("ix_vehicle_schedule_entries_vehicle_id"), "vehicle_schedule_entries", ["vehicle_id"], unique=False)
    op.create_table(
        "vehicle_service_records",
        sa.Column("vehicle_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("service_type", sa.Enum("INTERIM_SERVICE", "FULL_SERVICE", "MAJOR_SERVICE", "MANUFACTURER_SERVICE", name="servicetype", native_enum=False), nullable=False),
        sa.Column("next_service_due", sa.Date(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("status", sa.Enum("COMPLETED", "DUE_SOON", "OVERDUE", "SCHEDULED", name="servicestatus", native_enum=False), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vehicle_service_records_vehicle_id"), "vehicle_service_records", ["vehicle_id"], unique=False)
    op.create_table(
        "vehicle_defect_images",
        sa.Column("defect_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("uploaded_by_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(["defect_id"], ["vehicle_defects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uploaded_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(sa.schema.CreateSequence(sa.Sequence("fleet_number_seq")))
    op.add_column("vehicles", sa.Column("fleet_number", sa.String(length=20), server_default=sa.text("'VAN-' || lpad(nextval('fleet_number_seq')::text, 3, '0')"), nullable=False))
    op.add_column("vehicles", sa.Column("fleet_custom_name", sa.String(length=100), nullable=True))
    op.add_column("vehicles", sa.Column("cargo_volume_m3", sa.Float(), nullable=True))
    op.add_column("vehicles", sa.Column("max_payload_kg", sa.Float(), nullable=True))
    op.add_column("vehicles", sa.Column("average_mpg", sa.Float(), nullable=True))
    op.add_column("vehicles", sa.Column("range_miles", sa.Float(), nullable=True))
    op.add_column("vehicles", sa.Column("current_mileage", sa.Integer(), server_default="0", nullable=False))
    op.add_column("vehicles", sa.Column("service_interval_miles", sa.Integer(), nullable=True))
    op.add_column("vehicles", sa.Column("service_interval_months", sa.Integer(), nullable=True))
    op.add_column("vehicles", sa.Column("next_service_due", sa.Date(), nullable=True))
    op.add_column("vehicles", sa.Column("tax_due_date", sa.Date(), nullable=True))
    op.add_column("vehicles", sa.Column("insurance_provider", sa.String(length=200), nullable=True))
    op.add_column("vehicles", sa.Column("preferred_driver_id", sa.UUID(as_uuid=False), nullable=True))
    op.add_column(
        "vehicles",
        sa.Column("live_status", sa.Enum("OUT_FOR_DELIVERY", "OUT_FOR_PICKUP", "IDLE", "COMPLETED", name="livestatus", native_enum=False), server_default="IDLE", nullable=False),
    )
    op.add_column("vehicles", sa.Column("availability_effective_from", sa.DateTime(timezone=True), nullable=True))
    op.add_column("vehicles", sa.Column("availability_effective_to", sa.DateTime(timezone=True), nullable=True))
    op.alter_column(
        "vehicles", "vehicle_type", existing_type=sa.VARCHAR(length=10), type_=sa.Enum("INTERNAL", "EXTERNAL", name="vehicletype", native_enum=False), existing_nullable=False
    )
    op.create_index("ix_vehicles_created_at", "vehicles", ["created_at"], unique=False)
    op.create_index(op.f("ix_vehicles_fleet_number"), "vehicles", ["fleet_number"], unique=True)
    op.create_index(op.f("ix_vehicles_mot_expiry"), "vehicles", ["mot_expiry"], unique=False)
    op.create_index(op.f("ix_vehicles_preferred_driver_id"), "vehicles", ["preferred_driver_id"], unique=False)
    op.create_index(op.f("ix_vehicles_status"), "vehicles", ["status"], unique=False)
    op.create_index(op.f("ix_vehicles_tax_due_date"), "vehicles", ["tax_due_date"], unique=False)
    op.create_foreign_key("vehicles_preferred_driver_id_fkey", "vehicles", "users", ["preferred_driver_id"], ["id"], ondelete="SET NULL")
    op.drop_column("vehicles", "max_weight_kg")
    op.drop_column("vehicles", "notes")
    op.drop_column("vehicles", "max_volume_m3")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vehicles", sa.Column("max_volume_m3", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column("vehicles", sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column("vehicles", sa.Column("max_weight_kg", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint("vehicles_preferred_driver_id_fkey", "vehicles", type_="foreignkey")
    op.drop_index(op.f("ix_vehicles_tax_due_date"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_status"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_preferred_driver_id"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_mot_expiry"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_fleet_number"), table_name="vehicles")
    op.drop_index("ix_vehicles_created_at", table_name="vehicles")
    op.alter_column(
        "vehicles", "vehicle_type", existing_type=sa.Enum("INTERNAL", "EXTERNAL", name="vehicletype", native_enum=False), type_=sa.VARCHAR(length=10), existing_nullable=False
    )
    op.drop_column("vehicles", "availability_effective_to")
    op.drop_column("vehicles", "availability_effective_from")
    op.drop_column("vehicles", "live_status")
    op.drop_column("vehicles", "preferred_driver_id")
    op.drop_column("vehicles", "insurance_provider")
    op.drop_column("vehicles", "tax_due_date")
    op.drop_column("vehicles", "next_service_due")
    op.drop_column("vehicles", "service_interval_months")
    op.drop_column("vehicles", "service_interval_miles")
    op.drop_column("vehicles", "current_mileage")
    op.drop_column("vehicles", "range_miles")
    op.drop_column("vehicles", "average_mpg")
    op.drop_column("vehicles", "max_payload_kg")
    op.drop_column("vehicles", "cargo_volume_m3")
    op.drop_column("vehicles", "fleet_custom_name")
    op.drop_column("vehicles", "fleet_number")
    op.execute(sa.schema.DropSequence(sa.Sequence("fleet_number_seq")))
    op.drop_table("vehicle_defect_images")
    op.drop_index(op.f("ix_vehicle_service_records_vehicle_id"), table_name="vehicle_service_records")
    op.drop_table("vehicle_service_records")
    op.drop_index(op.f("ix_vehicle_schedule_entries_vehicle_id"), table_name="vehicle_schedule_entries")
    op.drop_index(op.f("ix_vehicle_schedule_entries_type"), table_name="vehicle_schedule_entries")
    op.drop_index(op.f("ix_vehicle_schedule_entries_date_from"), table_name="vehicle_schedule_entries")
    op.drop_table("vehicle_schedule_entries")
    op.drop_index("ix_vehicle_maintenance_records_vehicle_id_created_at", table_name="vehicle_maintenance_records")
    op.drop_table("vehicle_maintenance_records")
    op.drop_index(op.f("ix_vehicle_images_vehicle_id"), table_name="vehicle_images")
    op.drop_table("vehicle_images")
    op.drop_index("ix_vehicle_documents_vehicle_id_created_at", table_name="vehicle_documents")
    op.drop_table("vehicle_documents")
    op.drop_index(op.f("ix_vehicle_defects_vehicle_id"), table_name="vehicle_defects")
    op.drop_index(op.f("ix_vehicle_defects_route_id"), table_name="vehicle_defects")
    op.drop_table("vehicle_defects")
    # ### end Alembic commands ###
