"""Add suspension Rules and Supension Activity tables

Revision ID: 6698f60b0823
Revises: 6e7e45dafe47
Create Date: 2026-03-13 19:24:20.422051

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6698f60b0823"
down_revision: str | None = "6e7e45dafe47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "suspension_activity",
        sa.Column("rule_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("rule_name_snapshot", sa.String(length=255), nullable=False),
        sa.Column("account_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("conditions_met", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("action_taken", sa.String(length=32), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_suspension_activity_account_id"), "suspension_activity", ["account_id"], unique=False)
    op.create_index(op.f("ix_suspension_activity_rule_id"), "suspension_activity", ["rule_id"], unique=False)
    op.create_table(
        "suspension_rule",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("condition_summary", sa.String(length=255), nullable=False),
        sa.Column("logic", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("primary_trigger", sa.String(length=64), nullable=False),
        sa.Column("overdue_days_threshold", sa.Integer(), nullable=True),
        sa.Column("overdue_amount_threshold", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("credit_utilisation_threshold", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("additional_conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("suspension_type", sa.String(length=32), nullable=False),
        sa.Column("grace_period_days", sa.Integer(), nullable=True),
        sa.Column("notify_finance_team", sa.Boolean(), nullable=False),
        sa.Column("send_warning_to_user", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_suspension_rule_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("suspension_rule")
    op.drop_index(op.f("ix_suspension_activity_rule_id"), table_name="suspension_activity")
    op.drop_index(op.f("ix_suspension_activity_account_id"), table_name="suspension_activity")
    op.drop_table("suspension_activity")
    # ### end Alembic commands ###
