"""Updated Enum values to UPPERCASE

Revision ID: 6cc1ccedde23
Revises: 0007_invite_email_status
Create Date: 2026-03-07 15:29:41.666352

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6cc1ccedde23"
down_revision: str | None = "0007_invite_email_status"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_ROLE_MAP: list[tuple[str, str]] = [
    ("admin", "ADMIN"),
    ("super_admin", "ADMIN"),
    ("dispatcher", "ADMIN"),
    ("warehouse_staff", "WAREHOUSE_STAFF"),
    ("driver", "DRIVER"),
    ("customer_b2b", "CUSTOMER_B2B"),
    ("customer_b2c", "CUSTOMER_B2C"),
]

_STATUS_MAP: list[tuple[str, str]] = [
    ("active", "ACTIVE"),
    ("inactive", "INACTIVE"),
    ("suspended", "SUSPENDED"),
    ("pending_verification", "PENDING_VERIFICATION"),
]


def upgrade() -> None:
    op.drop_constraint("ck_users_role", "users", type_="check")
    conn = op.get_bind()
    for old, new in _ROLE_MAP:
        conn.execute(sa.text("UPDATE users SET role = :new WHERE role = :old"), {"new": new, "old": old})
        conn.execute(sa.text("UPDATE audit_log SET user_role = :new WHERE user_role = :old"), {"new": new, "old": old})
    for old, new in _STATUS_MAP:
        conn.execute(sa.text("UPDATE users SET status = :new WHERE status = :old"), {"new": new, "old": old})

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organizations",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum("ACTIVE", "INACTIVE", "SUSPENDED", name="organizationstatus", native_enum=False),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.Enum("ADMIN", "WAREHOUSE_STAFF", "DRIVER", "CUSTOMER_B2B", "CUSTOMER_B2C", name="userrole", native_enum=False),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "status",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.Enum("ACTIVE", "INACTIVE", "SUSPENDED", "PENDING_VERIFICATION", name="userstatus", native_enum=False),
        existing_nullable=False,
    )
    op.alter_column(
        "vehicles",
        "vehicle_type",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.Enum("VAN", "TRUCK", "CAR", "BIKE", "CARGO_BIKE", name="vehicletype", native_enum=False),
        existing_nullable=False,
    )
    op.alter_column(
        "vehicles",
        "fuel_type",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum("PETROL", "DIESEL", "ELECTRIC", "HYBRID", name="fueltype", native_enum=False),
        existing_nullable=False,
    )
    op.alter_column(
        "vehicles",
        "status",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.Enum("ACTIVE", "INACTIVE", "MAINTENANCE", "DECOMMISSIONED", name="vehiclestatus", native_enum=False),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vehicles",
        "status",
        existing_type=sa.Enum("ACTIVE", "INACTIVE", "MAINTENANCE", "DECOMMISSIONED", name="vehiclestatus", native_enum=False),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "vehicles",
        "fuel_type",
        existing_type=sa.Enum("PETROL", "DIESEL", "ELECTRIC", "HYBRID", name="fueltype", native_enum=False),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "vehicles",
        "vehicle_type",
        existing_type=sa.Enum("VAN", "TRUCK", "CAR", "BIKE", "CARGO_BIKE", name="vehicletype", native_enum=False),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "status",
        existing_type=sa.Enum("ACTIVE", "INACTIVE", "SUSPENDED", "PENDING_VERIFICATION", name="userstatus", native_enum=False),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "role",
        existing_type=sa.Enum("ADMIN", "WAREHOUSE_STAFF", "DRIVER", "CUSTOMER_B2B", "CUSTOMER_B2C", name="userrole", native_enum=False),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "organizations",
        "status",
        existing_type=sa.Enum("ACTIVE", "INACTIVE", "SUSPENDED", name="organizationstatus", native_enum=False),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    # ### end Alembic commands ###

    conn = op.get_bind()
    for old, new in _ROLE_MAP:
        conn.execute(sa.text("UPDATE users SET role = :old WHERE role = :new"), {"old": old, "new": new})
        conn.execute(sa.text("UPDATE audit_log SET user_role = :old WHERE user_role = :new"), {"old": old, "new": new})
    for old, new in _STATUS_MAP:
        conn.execute(sa.text("UPDATE users SET status = :old WHERE status = :new"), {"old": old, "new": new})
    op.create_check_constraint(
        "ck_users_role",
        "users",
        "role IN ('admin','warehouse_staff','driver','customer_b2b','customer_b2c')",
    )
