"""improve holiday model

Revision ID: 717fa4abcfe9
Revises: 80dc8ef71af4
Create Date: 2026-03-12 19:52:10.455275

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "717fa4abcfe9"
down_revision: str | None = "80dc8ef71af4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
