"""Added Table for holidays.

Revision ID: 80dc8ef71af4
Revises: 0010_access_jti
Create Date: 2026-03-12 19:20:24.620262

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80dc8ef71af4"
down_revision: str | None = "0010_access_jti"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "holidays",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("audience", sa.String(length=16), nullable=False),
        sa.Column("allow_shifts", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_holidays_year"), "holidays", ["year"], unique=False)
    op.create_table(
        "holiday_allowed_drivers",
        sa.Column("holiday_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("driver_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["holiday_id"], ["holidays.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("holiday_id", "driver_id", name="uq_holiday_allowed_driver_holiday_driver"),
    )
    op.create_index(op.f("ix_holiday_allowed_drivers_driver_id"), "holiday_allowed_drivers", ["driver_id"], unique=False)
    op.create_index(op.f("ix_holiday_allowed_drivers_holiday_id"), "holiday_allowed_drivers", ["holiday_id"], unique=False)
    # op.drop_index(op.f("ix_driver_traffic_violations_driver_id"), table_name="driver_traffic_violations")
    # op.drop_table("driver_traffic_violations")
    # op.drop_index(op.f("ix_driver_time_off_driver_id"), table_name="driver_time_off")
    # op.drop_table("driver_time_off")
    # op.drop_index(op.f("ix_driver_weekly_schedule_driver_id"), table_name="driver_weekly_schedule")
    # op.drop_table("driver_weekly_schedule")
    # op.drop_index(op.f("ix_driver_documents_driver_id"), table_name="driver_documents")
    # op.drop_table("driver_documents")
    # op.add_column("drivers", sa.Column("status", sa.String(length=30), nullable=False))
    # op.drop_index(op.f("ix_drivers_driver_code"), table_name="drivers")
    # op.drop_column("drivers", "email")
    # op.drop_column("drivers", "first_name")
    # op.drop_column("drivers", "profile_photo_key")
    # op.drop_column("drivers", "capacity")
    # op.drop_column("drivers", "last_name")
    # op.drop_column("drivers", "live_status")
    # op.drop_column("drivers", "phone")
    # op.drop_column("drivers", "safety_score")
    # op.drop_column("drivers", "postcode")
    # op.drop_column("drivers", "account_status")
    # op.drop_column("drivers", "address_line2")
    # op.drop_column("drivers", "driver_code")
    # op.drop_column("drivers", "address_line1")
    # op.drop_column("drivers", "driver_type")
    # op.drop_column("drivers", "city")
    # op.drop_column("drivers", "on_time_deliveries")
    # # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column("drivers", sa.Column("on_time_deliveries", sa.INTEGER(), autoincrement=False, nullable=True))
    # op.add_column("drivers", sa.Column("city", sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # op.add_column("drivers", sa.Column("driver_type", sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # op.add_column("drivers", sa.Column("address_line1", sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # op.add_column("drivers", sa.Column("driver_code", sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # op.add_column("drivers", sa.Column("address_line2", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # op.add_column("drivers", sa.Column("account_status", sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    # op.add_column("drivers", sa.Column("postcode", sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # op.add_column("drivers", sa.Column("safety_score", sa.INTEGER(), autoincrement=False, nullable=True))
    # op.add_column("drivers", sa.Column("phone", sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # op.add_column("drivers", sa.Column("live_status", sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    # op.add_column("drivers", sa.Column("last_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # op.add_column("drivers", sa.Column("capacity", sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # op.add_column("drivers", sa.Column("profile_photo_key", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # op.add_column("drivers", sa.Column("first_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # op.add_column("drivers", sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # op.create_index(op.f("ix_drivers_driver_code"), "drivers", ["driver_code"], unique=True)
    # op.drop_column("drivers", "status")
    # op.create_table(
    #     "driver_documents",
    #     sa.Column("driver_id", sa.UUID(), autoincrement=False, nullable=False),
    #     sa.Column(
    #         "kind", postgresql.ENUM("DRIVING_LICENCE", "CPC_CERTIFICATE", "DIGITAL_TACHOGRAPH", "CUSTOM", name="driver_document_kind_enum"), autoincrement=False, nullable=False
    #     ),
    #     sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    #     sa.Column("file_key", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    #     sa.Column("expiry_date", sa.DATE(), autoincrement=False, nullable=True),
    #     sa.Column("content_type", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    #     sa.Column("size_bytes", sa.INTEGER(), autoincrement=False, nullable=True),
    #     sa.Column("is_initial", sa.BOOLEAN(), autoincrement=False, nullable=False),
    #     sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
    #     sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=False),
    #     sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=False),
    #     sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], name=op.f("driver_documents_driver_id_fkey"), ondelete="CASCADE"),
    #     sa.PrimaryKeyConstraint("id", name=op.f("driver_documents_pkey")),
    # )
    # op.create_index(op.f("ix_driver_documents_driver_id"), "driver_documents", ["driver_id"], unique=False)
    # op.create_table(
    #     "driver_weekly_schedule",
    #     sa.Column("driver_id", sa.UUID(), autoincrement=False, nullable=False),
    #     sa.Column("day_of_week", sa.INTEGER(), autoincrement=False, nullable=False),
    #     sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    #     sa.Column("start_time", postgresql.TIME(), autoincrement=False, nullable=True),
    #     sa.Column("end_time", postgresql.TIME(), autoincrement=False, nullable=True),
    #     sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
    #     sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=False),
    #     sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=False),
    #     sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], name=op.f("driver_weekly_schedule_driver_id_fkey"), ondelete="CASCADE"),
    #     sa.PrimaryKeyConstraint("id", name=op.f("driver_weekly_schedule_pkey")),
    # )
    # op.create_index(op.f("ix_driver_weekly_schedule_driver_id"), "driver_weekly_schedule", ["driver_id"], unique=False)
    # op.create_table(
    #     "driver_time_off",
    #     sa.Column("driver_id", sa.UUID(), autoincrement=False, nullable=False),
    #     sa.Column("start_date", sa.DATE(), autoincrement=False, nullable=False),
    #     sa.Column("end_date", sa.DATE(), autoincrement=False, nullable=False),
    #     sa.Column("type", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    #     sa.Column("days", sa.INTEGER(), autoincrement=False, nullable=True),
    #     sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
    #     sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=False),
    #     sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=False),
    #     sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
    #     sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], name=op.f("driver_time_off_driver_id_fkey"), ondelete="CASCADE"),
    #     sa.PrimaryKeyConstraint("id", name=op.f("driver_time_off_pkey")),
    # )
    # op.create_index(op.f("ix_driver_time_off_driver_id"), "driver_time_off", ["driver_id"], unique=False)
    # op.create_table(
    #     "driver_traffic_violations",
    #     sa.Column("driver_id", sa.UUID(), autoincrement=False, nullable=False),
    #     sa.Column("occurred_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    #     sa.Column("violation_type", postgresql.ENUM("SPEEDING", "RED_LIGHT", "PARKING", "BUS_LANE", name="traffic_violation_type_enum"), autoincrement=False, nullable=False),
    #     sa.Column("amount", sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    #     sa.Column("status", postgresql.ENUM("UNPAID", "PAID", name="traffic_violation_status_enum"), autoincrement=False, nullable=False),
    #     sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
    #     sa.Column("proof_key", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    #     sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
    #     sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=False),
    #     sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=False),
    #     sa.Column("version", sa.INTEGER(), server_default=sa.text("1"), autoincrement=False, nullable=False),
    #     sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], name=op.f("driver_traffic_violations_driver_id_fkey"), ondelete="CASCADE"),
    #     sa.PrimaryKeyConstraint("id", name=op.f("driver_traffic_violations_pkey")),
    # )
    # op.create_index(op.f("ix_driver_traffic_violations_driver_id"), "driver_traffic_violations", ["driver_id"], unique=False)
    op.drop_index(op.f("ix_holiday_allowed_drivers_holiday_id"), table_name="holiday_allowed_drivers")
    op.drop_index(op.f("ix_holiday_allowed_drivers_driver_id"), table_name="holiday_allowed_drivers")
    op.drop_table("holiday_allowed_drivers")
    op.drop_index(op.f("ix_holidays_year"), table_name="holidays")
    op.drop_table("holidays")
    # ### end Alembic commands ###
