"""add_org_crud_and_invite_activation

Revision ID: 84429907deda
Revises: 42e057ee7632
Create Date: 2026-03-10 00:38:57.714303

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84429907deda"
down_revision: str | None = "42e057ee7632"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invites", sa.Column("verification_code_hash", sa.String(length=255), nullable=True))
    op.add_column("invites", sa.Column("code_expires_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("invites", sa.Column("code_verified_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invites", "code_verified_at")
    op.drop_column("invites", "code_expires_at")
    op.drop_column("invites", "verification_code_hash")
    # ### end Alembic commands ###
