"""add is_paid bool to DriverTimeOff Table, Admin can now mark leave as paid/unpaid

Revision ID: 8d03226dfb50
Revises: a1b2c3d4e5f6
Create Date: 2026-03-12 11:28:10.656163

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d03226dfb50"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("driver_time_off", sa.Column("is_paid", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("driver_time_off", "is_paid")
    # ### end Alembic commands ###
