"""create_all_tables

Revision ID: da8153402035
Revises: 0001_ext
Create Date: 2026-02-21 16:38:44.406675

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da8153402035"
down_revision: str | None = "0001_ext"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_templates",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("variables", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=True),
        sa.Column("registration_number", sa.String(length=100), nullable=True),
        sa.Column("contact_name", sa.String(length=255), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("contact_phone", sa.String(length=50), nullable=True),
        sa.Column("billing_email", sa.String(length=255), nullable=True),
        sa.Column("billing_address", sa.Text(), nullable=True),
        sa.Column("vat_number", sa.String(length=50), nullable=True),
        sa.Column("api_key_hash", sa.String(length=255), nullable=True),
        sa.Column("api_key_prefix", sa.String(length=10), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pricing_rules",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("rule_type", sa.String(length=30), nullable=False),
        sa.Column("service_tier", sa.String(length=30), nullable=True),
        sa.Column("min_value", sa.Float(), nullable=True),
        sa.Column("max_value", sa.Float(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("is_percentage", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "regions",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "boundary",
            geoalchemy2.types.Geometry(geometry_type="POLYGON", srid=4326, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    # NOTE: idx_regions_boundary is auto-created by GeoAlchemy2 spatial_index=True
    op.create_table(
        "depots",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("address_line_1", sa.String(length=255), nullable=False),
        sa.Column("address_line_2", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("postcode", sa.String(length=20), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(geometry_type="POINT", srid=4326, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("region_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["region_id"], ["regions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    # NOTE: idx_depots_location is auto-created by GeoAlchemy2 spatial_index=True
    op.create_index(op.f("ix_depots_region_id"), "depots", ["region_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False),
        sa.Column("mfa_secret", sa.String(length=255), nullable=True),
        sa.Column("mfa_backup_codes", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("region_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("processing_objected", sa.Boolean(), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "role IN ('super_admin','admin','dispatcher','warehouse_staff','driver','customer_b2b','customer_b2c')",
            name="ck_users_role",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["region_id"], ["regions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_index(op.f("ix_users_region_id"), "users", ["region_id"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "addresses",
        sa.Column("line_1", sa.String(length=255), nullable=False),
        sa.Column("line_2", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("county", sa.String(length=100), nullable=True),
        sa.Column("postcode", sa.String(length=20), nullable=False),
        sa.Column("country", sa.String(length=10), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(geometry_type="POINT", srid=4326, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column("uprn", sa.String(length=20), nullable=True),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # NOTE: idx_addresses_location is auto-created by GeoAlchemy2 spatial_index=True
    op.create_index(op.f("ix_addresses_postcode"), "addresses", ["postcode"], unique=False)
    op.create_index(op.f("ix_addresses_uprn"), "addresses", ["uprn"], unique=False)
    op.create_index(op.f("ix_addresses_user_id"), "addresses", ["user_id"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("user_role", sa.String(length=30), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("old_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(op.f("ix_audit_log_entity_id"), "audit_log", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_log_entity_type"), "audit_log", ["entity_type"], unique=False)
    op.create_index(op.f("ix_audit_log_user_id"), "audit_log", ["user_id"], unique=False)
    op.create_table(
        "notification_log",
        sa.Column("recipient_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("recipient_address", sa.String(length=255), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("template_name", sa.String(length=100), nullable=True),
        sa.Column("subject", sa.String(length=255), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("external_id", sa.String(length=100), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["recipient_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notification_log_channel"), "notification_log", ["channel"], unique=False)
    op.create_index(op.f("ix_notification_log_recipient_id"), "notification_log", ["recipient_id"], unique=False)
    op.create_table(
        "payment_methods",
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("braintree_token", sa.String(length=255), nullable=False),
        sa.Column("card_type", sa.String(length=30), nullable=True),
        sa.Column("last_four", sa.String(length=4), nullable=True),
        sa.Column("expiry_month", sa.Integer(), nullable=True),
        sa.Column("expiry_year", sa.Integer(), nullable=True),
        sa.Column("cardholder_name", sa.String(length=255), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payment_methods_user_id"), "payment_methods", ["user_id"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True)
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "route_plans",
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("depot_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["depot_id"], ["depots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["locked_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("depot_id", "service_date", name="uq_route_plans_depot_date"),
    )
    op.create_index(op.f("ix_route_plans_depot_id"), "route_plans", ["depot_id"], unique=False)
    op.create_index(op.f("ix_route_plans_service_date"), "route_plans", ["service_date"], unique=False)
    op.create_table(
        "vehicles",
        sa.Column("registration_number", sa.String(length=20), nullable=False),
        sa.Column("make", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("vehicle_type", sa.String(length=30), nullable=False),
        sa.Column("fuel_type", sa.String(length=20), nullable=False),
        sa.Column("max_weight_kg", sa.Float(), nullable=True),
        sa.Column("max_volume_m3", sa.Float(), nullable=True),
        sa.Column("mot_expiry", sa.Date(), nullable=True),
        sa.Column("insurance_expiry", sa.Date(), nullable=True),
        sa.Column("insurance_policy_number", sa.String(length=100), nullable=True),
        sa.Column("depot_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["depot_id"], ["depots.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vehicles_depot_id"), "vehicles", ["depot_id"], unique=False)
    op.create_index(op.f("ix_vehicles_registration_number"), "vehicles", ["registration_number"], unique=True)
    op.create_table(
        "warehouse_zones",
        sa.Column("depot_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("zone_type", sa.String(length=30), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["depot_id"], ["depots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_warehouse_zones_depot_id"), "warehouse_zones", ["depot_id"], unique=False)
    op.create_table(
        "bookings",
        sa.Column("reference_number", sa.String(length=30), nullable=False),
        sa.Column("customer_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("contact_name", sa.String(length=255), nullable=False),
        sa.Column("contact_email", sa.String(length=255), nullable=False),
        sa.Column("contact_phone", sa.String(length=50), nullable=False),
        sa.Column("pickup_address_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("pickup_instructions", sa.Text(), nullable=True),
        sa.Column("service_tier", sa.String(length=30), nullable=False),
        sa.Column("special_instructions", sa.Text(), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("vat_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("price_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("payment_status", sa.String(length=30), nullable=False),
        sa.Column("payment_method_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("braintree_transaction_id", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("tracking_token", sa.String(length=255), nullable=True),
        sa.Column("tracking_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["customer_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["payment_method_id"], ["payment_methods.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["pickup_address_id"], ["addresses.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tracking_token"),
    )
    op.create_index(op.f("ix_bookings_customer_id"), "bookings", ["customer_id"], unique=False)
    op.create_index(op.f("ix_bookings_organization_id"), "bookings", ["organization_id"], unique=False)
    op.create_index(op.f("ix_bookings_reference_number"), "bookings", ["reference_number"], unique=True)
    op.create_index(op.f("ix_bookings_status"), "bookings", ["status"], unique=False)
    op.create_table(
        "drivers",
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("depot_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("vehicle_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("license_number", sa.String(length=50), nullable=True),
        sa.Column("license_category", sa.String(length=20), nullable=True),
        sa.Column("max_stops", sa.Integer(), nullable=False),
        sa.Column("territory_tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["depot_id"], ["depots.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_drivers_depot_id"), "drivers", ["depot_id"], unique=False)
    op.create_index(op.f("ix_drivers_user_id"), "drivers", ["user_id"], unique=True)
    op.create_index(op.f("ix_drivers_vehicle_id"), "drivers", ["vehicle_id"], unique=False)
    op.create_table(
        "planning_audit_log",
        sa.Column("plan_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("actor_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["plan_id"], ["route_plans.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_planning_audit_log_plan_id"), "planning_audit_log", ["plan_id"], unique=False)
    op.create_table(
        "delivery_stops",
        sa.Column("booking_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("recipient_name", sa.String(length=255), nullable=False),
        sa.Column("recipient_phone", sa.String(length=50), nullable=True),
        sa.Column("recipient_email", sa.String(length=255), nullable=True),
        sa.Column("address_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("time_window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivery_preference", sa.String(length=30), nullable=True),
        sa.Column("delivery_instructions", sa.Text(), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["address_id"], ["addresses.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_delivery_stops_booking_id"), "delivery_stops", ["booking_id"], unique=False)
    op.create_table(
        "driver_shifts",
        sa.Column("driver_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("shift_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("driver_id", "shift_date", name="uq_driver_shifts_driver_date"),
    )
    op.create_index(op.f("ix_driver_shifts_driver_id"), "driver_shifts", ["driver_id"], unique=False)
    op.create_index(op.f("ix_driver_shifts_shift_date"), "driver_shifts", ["shift_date"], unique=False)
    op.create_table(
        "invoices",
        sa.Column("invoice_number", sa.String(length=30), nullable=False),
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("customer_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("booking_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("vat_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("vat_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("paid_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("braintree_transaction_id", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("pdf_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["customer_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoices_customer_id"), "invoices", ["customer_id"], unique=False)
    op.create_index(op.f("ix_invoices_invoice_number"), "invoices", ["invoice_number"], unique=True)
    op.create_index(op.f("ix_invoices_organization_id"), "invoices", ["organization_id"], unique=False)
    op.create_index(op.f("ix_invoices_status"), "invoices", ["status"], unique=False)
    op.create_table(
        "routes",
        sa.Column("plan_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("driver_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("vehicle_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("total_distance_km", sa.Float(), nullable=True),
        sa.Column("total_duration_min", sa.Float(), nullable=True),
        sa.Column("total_stops", sa.Integer(), nullable=False),
        sa.Column("total_weight_kg", sa.Float(), nullable=True),
        sa.Column("total_volume_m3", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["plan_id"], ["route_plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_routes_driver_id"), "routes", ["driver_id"], unique=False)
    op.create_index(op.f("ix_routes_plan_id"), "routes", ["plan_id"], unique=False)
    op.create_table(
        "vehicle_inspections",
        sa.Column("vehicle_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("driver_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("inspection_type", sa.String(length=30), nullable=False),
        sa.Column("result", sa.String(length=10), nullable=False),
        sa.Column("mileage", sa.Float(), nullable=True),
        sa.Column("checklist", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("photo_urls", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vehicle_inspections_driver_id"), "vehicle_inspections", ["driver_id"], unique=False)
    op.create_index(
        op.f("ix_vehicle_inspections_vehicle_id"),
        "vehicle_inspections",
        ["vehicle_id"],
        unique=False,
    )
    op.create_table(
        "waypoints",
        sa.Column("driver_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("altitude", sa.Float(), nullable=True),
        sa.Column("accuracy", sa.Float(), nullable=True),
        sa.Column("speed", sa.Float(), nullable=True),
        sa.Column("heading", sa.Float(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_waypoints_driver_id"), "waypoints", ["driver_id"], unique=False)
    op.create_index(op.f("ix_waypoints_recorded_at"), "waypoints", ["recorded_at"], unique=False)
    op.create_table(
        "packages",
        sa.Column("tracking_id", sa.String(length=30), nullable=False),
        sa.Column("booking_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("delivery_stop_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("length_cm", sa.Float(), nullable=True),
        sa.Column("width_cm", sa.Float(), nullable=True),
        sa.Column("height_cm", sa.Float(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("declared_value", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("special_handling", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("is_fragile", sa.Boolean(), nullable=False),
        sa.Column("requires_signature", sa.Boolean(), nullable=False),
        sa.Column("safe_place_allowed", sa.Boolean(), nullable=False),
        sa.Column("keep_upright", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("is_damaged", sa.Boolean(), nullable=False),
        sa.Column("damage_type", sa.String(length=50), nullable=True),
        sa.Column("damage_description", sa.Text(), nullable=True),
        sa.Column("damage_photo_urls", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("damage_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("warehouse_zone_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("shelf_location", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["delivery_stop_id"], ["delivery_stops.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["warehouse_zone_id"], ["warehouse_zones.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_packages_booking_id"), "packages", ["booking_id"], unique=False)
    op.create_index(op.f("ix_packages_delivery_stop_id"), "packages", ["delivery_stop_id"], unique=False)
    op.create_index(op.f("ix_packages_status"), "packages", ["status"], unique=False)
    op.create_index(op.f("ix_packages_tracking_id"), "packages", ["tracking_id"], unique=True)
    op.create_table(
        "route_stops",
        sa.Column("route_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("delivery_stop_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("assignment_source", sa.String(length=20), nullable=False),
        sa.Column("estimated_arrival", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_arrival", sa.DateTime(timezone=True), nullable=True),
        sa.Column("distance_from_prev_km", sa.Float(), nullable=True),
        sa.Column("duration_from_prev_min", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["delivery_stop_id"], ["delivery_stops.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["route_id"], ["routes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_route_stops_route_id"), "route_stops", ["route_id"], unique=False)
    op.create_table(
        "delivery_attempts",
        sa.Column("package_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("delivery_stop_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("driver_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=40), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("pod_photo_urls", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(["delivery_stop_id"], ["delivery_stops.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["package_id"], ["packages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_delivery_attempts_package_id"), "delivery_attempts", ["package_id"], unique=False)
    op.create_table(
        "invoice_line_items",
        sa.Column("invoice_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("package_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("line_type", sa.String(length=30), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["package_id"], ["packages.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoice_line_items_invoice_id"), "invoice_line_items", ["invoice_id"], unique=False)
    op.create_table(
        "shipment_events",
        sa.Column("package_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("booking_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("from_status", sa.String(length=40), nullable=True),
        sa.Column("to_status", sa.String(length=40), nullable=False),
        sa.Column("triggered_by_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("triggered_by_role", sa.String(length=30), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["package_id"], ["packages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["triggered_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shipment_events_booking_id"), "shipment_events", ["booking_id"], unique=False)
    op.create_index(op.f("ix_shipment_events_package_id"), "shipment_events", ["package_id"], unique=False)
    # NOTE: spatial_ref_sys is a PostGIS system table — do NOT drop it.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: spatial_ref_sys is a PostGIS system table — do NOT touch it.
    op.drop_index(op.f("ix_shipment_events_package_id"), table_name="shipment_events")
    op.drop_index(op.f("ix_shipment_events_booking_id"), table_name="shipment_events")
    op.drop_table("shipment_events")
    op.drop_index(op.f("ix_invoice_line_items_invoice_id"), table_name="invoice_line_items")
    op.drop_table("invoice_line_items")
    op.drop_index(op.f("ix_delivery_attempts_package_id"), table_name="delivery_attempts")
    op.drop_table("delivery_attempts")
    op.drop_index(op.f("ix_route_stops_route_id"), table_name="route_stops")
    op.drop_table("route_stops")
    op.drop_index(op.f("ix_packages_tracking_id"), table_name="packages")
    op.drop_index(op.f("ix_packages_status"), table_name="packages")
    op.drop_index(op.f("ix_packages_delivery_stop_id"), table_name="packages")
    op.drop_index(op.f("ix_packages_booking_id"), table_name="packages")
    op.drop_table("packages")
    op.drop_index(op.f("ix_waypoints_recorded_at"), table_name="waypoints")
    op.drop_index(op.f("ix_waypoints_driver_id"), table_name="waypoints")
    op.drop_table("waypoints")
    op.drop_index(op.f("ix_vehicle_inspections_vehicle_id"), table_name="vehicle_inspections")
    op.drop_index(op.f("ix_vehicle_inspections_driver_id"), table_name="vehicle_inspections")
    op.drop_table("vehicle_inspections")
    op.drop_index(op.f("ix_routes_plan_id"), table_name="routes")
    op.drop_index(op.f("ix_routes_driver_id"), table_name="routes")
    op.drop_table("routes")
    op.drop_index(op.f("ix_invoices_status"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_organization_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_invoice_number"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_customer_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_driver_shifts_shift_date"), table_name="driver_shifts")
    op.drop_index(op.f("ix_driver_shifts_driver_id"), table_name="driver_shifts")
    op.drop_table("driver_shifts")
    op.drop_index(op.f("ix_delivery_stops_booking_id"), table_name="delivery_stops")
    op.drop_table("delivery_stops")
    op.drop_index(op.f("ix_planning_audit_log_plan_id"), table_name="planning_audit_log")
    op.drop_table("planning_audit_log")
    op.drop_index(op.f("ix_drivers_vehicle_id"), table_name="drivers")
    op.drop_index(op.f("ix_drivers_user_id"), table_name="drivers")
    op.drop_index(op.f("ix_drivers_depot_id"), table_name="drivers")
    op.drop_table("drivers")
    op.drop_index(op.f("ix_bookings_status"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_reference_number"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_organization_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_customer_id"), table_name="bookings")
    op.drop_table("bookings")
    op.drop_index(op.f("ix_warehouse_zones_depot_id"), table_name="warehouse_zones")
    op.drop_table("warehouse_zones")
    op.drop_index(op.f("ix_vehicles_registration_number"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_depot_id"), table_name="vehicles")
    op.drop_table("vehicles")
    op.drop_index(op.f("ix_route_plans_service_date"), table_name="route_plans")
    op.drop_index(op.f("ix_route_plans_depot_id"), table_name="route_plans")
    op.drop_table("route_plans")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_payment_methods_user_id"), table_name="payment_methods")
    op.drop_table("payment_methods")
    op.drop_index(op.f("ix_notification_log_recipient_id"), table_name="notification_log")
    op.drop_index(op.f("ix_notification_log_channel"), table_name="notification_log")
    op.drop_table("notification_log")
    op.drop_index(op.f("ix_audit_log_user_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_entity_type"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_entity_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_addresses_user_id"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_uprn"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_postcode"), table_name="addresses")
    # NOTE: idx_addresses_location is auto-dropped with the table by GeoAlchemy2
    op.drop_table("addresses")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_region_id"), table_name="users")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_depots_region_id"), table_name="depots")
    # NOTE: idx_depots_location is auto-dropped with the table by GeoAlchemy2
    op.drop_table("depots")
    # NOTE: idx_regions_boundary is auto-dropped with the table by GeoAlchemy2
    op.drop_table("regions")
    op.drop_table("pricing_rules")
    op.drop_table("organizations")
    op.drop_table("notification_templates")
    # ### end Alembic commands ###
