"""remove seperate sick leave table, all leave types ar enow handled in one central time-off table

Revision ID: dc6f35907587
Revises: 0309ba573191
Create Date: 2026-03-11 13:15:01.695371

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc6f35907587"
down_revision: str | None = "0309ba573191"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_driver_sick_leave_driver_id"), table_name="driver_sick_leave")
    op.drop_table("driver_sick_leave")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "driver_sick_leave",
        sa.Column("driver_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("start_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("end_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("doctor_note_key", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("days_deducted", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("remaining_balance_days", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], name=op.f("driver_sick_leave_driver_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("driver_sick_leave_pkey")),
    )
    op.create_index(op.f("ix_driver_sick_leave_driver_id"), "driver_sick_leave", ["driver_id"], unique=False)
    # ### end Alembic commands ###
