"""Updates on vehicle related models - revisions

Revision ID: e363b2b7b2e2
Revises: 0023_org_on_hold_status
Create Date: 2026-03-24 10:07:31.174149

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e363b2b7b2e2"
down_revision: Union[str, None] = "0023_org_on_hold_status"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column("vehicle_documents", "policy_number", new_column_name="reference_number")
    op.alter_column(
        "vehicle_documents",
        "title",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.execute(sa.text("CREATE SEQUENCE IF NOT EXISTS maintenance_ref_seq START 1 INCREMENT 1"))
    op.add_column(
        "vehicle_maintenance_records",
        sa.Column("reference", sa.String(length=32), server_default=sa.text("'MT-' || lpad(nextval('maintenance_ref_seq')::text, 5, '0')"), nullable=False),
    )
    op.create_index(op.f("ix_vehicle_maintenance_records_reference"), "vehicle_maintenance_records", ["reference"], unique=True)
    op.execute(sa.text("""
            UPDATE vehicle_maintenance_records AS v
            SET reference = 'MT-' || LPAD(s.rn::text, 5, '0')
            FROM (
                SELECT id, row_number() OVER (ORDER BY created_at) AS rn
                FROM vehicle_maintenance_records
            ) AS s
            WHERE v.id = s.id
            """))
    op.execute(sa.text("""
            SELECT setval(
                'maintenance_ref_seq',
                GREATEST(
                    COALESCE(
                        (SELECT MAX(
                            CAST(NULLIF(SUBSTRING(reference FROM 4), '') AS INTEGER)
                        ) FROM vehicle_maintenance_records WHERE reference ~ '^MT-[0-9]+$'),
                        0
                    ),
                    1
                )
            )
            """))
    op.alter_column("vehicles", "availability_effective_from", existing_type=postgresql.TIMESTAMP(timezone=True), type_=sa.Date(), existing_nullable=True)
    op.alter_column("vehicles", "availability_effective_to", existing_type=postgresql.TIMESTAMP(timezone=True), type_=sa.Date(), existing_nullable=True)
    op.drop_column("vehicles", "insurance_provider")
    op.drop_column("vehicles", "insurance_policy_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vehicles", sa.Column("insurance_policy_number", sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column("vehicles", sa.Column("insurance_provider", sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.alter_column("vehicles", "availability_effective_to", existing_type=sa.Date(), type_=postgresql.TIMESTAMP(timezone=True), existing_nullable=True)
    op.alter_column("vehicles", "availability_effective_from", existing_type=sa.Date(), type_=postgresql.TIMESTAMP(timezone=True), existing_nullable=True)
    op.drop_index(op.f("ix_vehicle_maintenance_records_reference"), table_name="vehicle_maintenance_records")
    op.drop_column("vehicle_maintenance_records", "reference")
    op.execute(sa.text("DROP SEQUENCE IF EXISTS maintenance_ref_seq"))
    op.alter_column(
        "vehicle_documents",
        "title",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column("vehicle_documents", "reference_number", new_column_name="policy_number")

    # ### end Alembic commands ###
