"""Create_driver's_figma_related_tables

Revision ID: f4670f5faf8d
Revises: 0015_org_logo_phone
Create Date: 2026-03-10 16:09:59.886723

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4670f5faf8d"
down_revision: str | None = "0015_org_logo_phone"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "driver_documents",
        sa.Column("driver_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("file_key", sa.String(length=255), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("is_initial", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_driver_documents_driver_id"), "driver_documents", ["driver_id"], unique=False)
    op.create_table(
        "driver_sick_leave",
        sa.Column("driver_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("doctor_note_key", sa.String(length=255), nullable=True),
        sa.Column("days_deducted", sa.Integer(), nullable=True),
        sa.Column("remaining_balance_days", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_driver_sick_leave_driver_id"), "driver_sick_leave", ["driver_id"], unique=False)
    op.create_table(
        "driver_time_off",
        sa.Column("driver_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("days", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_driver_time_off_driver_id"), "driver_time_off", ["driver_id"], unique=False)
    op.create_table(
        "driver_traffic_violations",
        sa.Column("driver_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("violation_type", sa.String(length=50), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("proof_key", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_driver_traffic_violations_driver_id"), "driver_traffic_violations", ["driver_id"], unique=False)
    op.create_table(
        "driver_weekly_schedule",
        sa.Column("driver_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_driver_weekly_schedule_driver_id"), "driver_weekly_schedule", ["driver_id"], unique=False)
    op.add_column("drivers", sa.Column("driver_code", sa.String(length=20), nullable=False))
    op.add_column("drivers", sa.Column("first_name", sa.String(length=100), nullable=False))
    op.add_column("drivers", sa.Column("last_name", sa.String(length=100), nullable=False))
    op.add_column("drivers", sa.Column("email", sa.String(length=255), nullable=False))
    op.add_column("drivers", sa.Column("phone", sa.String(length=50), nullable=True))
    op.add_column("drivers", sa.Column("capacity", sa.String(length=20), nullable=False))
    op.add_column("drivers", sa.Column("driver_type", sa.String(length=20), nullable=False))
    op.add_column("drivers", sa.Column("account_status", sa.String(length=30), nullable=False))
    op.add_column("drivers", sa.Column("live_status", sa.String(length=30), nullable=False))
    op.add_column("drivers", sa.Column("safety_score", sa.Integer(), nullable=True))
    op.add_column("drivers", sa.Column("on_time_deliveries", sa.Integer(), nullable=True))
    op.add_column("drivers", sa.Column("address_line1", sa.String(length=255), nullable=False))
    op.add_column("drivers", sa.Column("address_line2", sa.String(length=255), nullable=True))
    op.add_column("drivers", sa.Column("city", sa.String(length=100), nullable=False))
    op.add_column("drivers", sa.Column("postcode", sa.String(length=20), nullable=False))
    op.add_column("drivers", sa.Column("profile_photo_key", sa.String(length=255), nullable=True))
    op.create_index(op.f("ix_drivers_driver_code"), "drivers", ["driver_code"], unique=True)
    op.drop_column("drivers", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("drivers", sa.Column("status", sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_index(op.f("ix_drivers_driver_code"), table_name="drivers")
    op.drop_column("drivers", "profile_photo_key")
    op.drop_column("drivers", "postcode")
    op.drop_column("drivers", "city")
    op.drop_column("drivers", "address_line2")
    op.drop_column("drivers", "address_line1")
    op.drop_column("drivers", "on_time_deliveries")
    op.drop_column("drivers", "safety_score")
    op.drop_column("drivers", "live_status")
    op.drop_column("drivers", "account_status")
    op.drop_column("drivers", "driver_type")
    op.drop_column("drivers", "capacity")
    op.drop_column("drivers", "phone")
    op.drop_column("drivers", "email")
    op.drop_column("drivers", "last_name")
    op.drop_column("drivers", "first_name")
    op.drop_column("drivers", "driver_code")
    op.drop_index(op.f("ix_driver_weekly_schedule_driver_id"), table_name="driver_weekly_schedule")
    op.drop_table("driver_weekly_schedule")
    op.drop_index(op.f("ix_driver_traffic_violations_driver_id"), table_name="driver_traffic_violations")
    op.drop_table("driver_traffic_violations")
    op.drop_index(op.f("ix_driver_time_off_driver_id"), table_name="driver_time_off")
    op.drop_table("driver_time_off")
    op.drop_index(op.f("ix_driver_sick_leave_driver_id"), table_name="driver_sick_leave")
    op.drop_table("driver_sick_leave")
    op.drop_index(op.f("ix_driver_documents_driver_id"), table_name="driver_documents")
    op.drop_table("driver_documents")
    # ### end Alembic commands ###
