"""Stable error codes returned in API error responses.

Frontends can switch on these values. Keep in sync with exception handlers
and any place that builds error responses.
"""

import enum


class ErrorCode(enum.StrEnum):
    """Machine-readable error code for APIResponse.error.code."""

    APP_ERROR = "APP_ERROR"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    FORBIDDEN = "FORBIDDEN"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    PAYMENT_NONCE_INVALID = "PAYMENT_NONCE_INVALID"
    BANK_AUTHENTICATION_REQUIRED = "BANK_AUTHENTICATION_REQUIRED"
    BANK_VERIFICATION_FAILED = "BANK_VERIFICATION_FAILED"
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    API_KEY_ERROR = "API_KEY_ERROR"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    HTTP_ERROR = "HTTP_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    PAYMENT_PROVIDER_UNAVAILABLE = "PAYMENT_PROVIDER_UNAVAILABLE"
