"""Billing module enums."""

import enum


class PaymentRecordStatus(enum.StrEnum):
    """Lifecycle status for a recorded payment."""

    DEPOSITED = "DEPOSITED"
    NOT_DEPOSITED = "NOT_DEPOSITED"
    PENDING = "PENDING"
    WITHHELD_RETURNED = "WITHHELD_RETURNED"
    VOIDED = "VOIDED"


class AllocationStatus(enum.StrEnum):
    """Allocation completeness status for a payment."""

    ALLOCATED = "ALLOCATED"
    PARTIALLY_ALLOCATED = "PARTIALLY_ALLOCATED"
    UNALLOCATED = "UNALLOCATED"


class PaymentProvider(enum.StrEnum):
    """Source/provider of the payment."""

    BRAINTREE = "BRAINTREE"
    MANUAL = "MANUAL"
    BANK_TRANSFER = "BANK_TRANSFER"
    CHEQUE = "CHEQUE"
    OTHER = "OTHER"


class PaymentEventType(enum.StrEnum):
    """Append-only billing payment event types."""

    RECORDED = "RECORDED"
    STATUS_CHANGED = "STATUS_CHANGED"
    BRAINTREE_STATUS_CHANGED = "BRAINTREE_STATUS_CHANGED"
    BRAINTREE_DISPUTE_CHANGED = "BRAINTREE_DISPUTE_CHANGED"
    BRAINTREE_DISPUTE_OPENED = "BRAINTREE_DISPUTE_OPENED"
    BRAINTREE_DISPUTE_DISPUTED = "BRAINTREE_DISPUTE_DISPUTED"
    BRAINTREE_DISPUTE_UNDER_REVIEW = "BRAINTREE_DISPUTE_UNDER_REVIEW"
    BRAINTREE_DISPUTE_WON = "BRAINTREE_DISPUTE_WON"
    BRAINTREE_DISPUTE_LOST = "BRAINTREE_DISPUTE_LOST"
    BRAINTREE_DISPUTE_ACCEPTED = "BRAINTREE_DISPUTE_ACCEPTED"
    BRAINTREE_DISPUTE_EXPIRED = "BRAINTREE_DISPUTE_EXPIRED"
    BRAINTREE_DISPUTE_AUTO_ACCEPTED = "BRAINTREE_DISPUTE_AUTO_ACCEPTED"
    ALLOCATED = "ALLOCATED"
    ALLOCATION_REVISED = "ALLOCATION_REVISED"
    REMITTANCE_ADVICE_ATTACHED = "REMITTANCE_ADVICE_ATTACHED"
    REMITTANCE_ADVICE_REMOVED = "REMITTANCE_ADVICE_REMOVED"
    NOTES_UPDATED = "NOTES_UPDATED"
    VOIDED = "VOIDED"
    QB_SYNC_QUEUED = "QB_SYNC_QUEUED"
    QB_SYNC_COMPLETED = "QB_SYNC_COMPLETED"
    QB_SYNC_FAILED = "QB_SYNC_FAILED"


class RefundMethod(enum.StrEnum):
    CARD_REFUND = "CARD_REFUND"
    BANK_TRANSFER = "BANK_TRANSFER"
    CREDIT_NOTE = "CREDIT_NOTE"


class RefundType(enum.StrEnum):
    FULL = "FULL"
    PARTIAL = "PARTIAL"


class RefundStatus(enum.StrEnum):
    INITIATED = "INITIATED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    REVERSED = "REVERSED"


class RefundReasonCategory(enum.StrEnum):
    BOOKING_CANCELLED = "BOOKING_CANCELLED"
    SERVICE_FAILURE = "SERVICE_FAILURE"
    DUPLICATE_PAYMENT = "DUPLICATE_PAYMENT"
    BILLING_ERROR = "BILLING_ERROR"
    CLIENT_REQUEST = "CLIENT_REQUEST"
    VOIDED_INVOICE = "VOIDED_INVOICE"
    OTHER = "OTHER"


class RefundEventType(enum.StrEnum):
    INITIATED = "INITIATED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    BRAINTREE_STATUS_CHANGED = "BRAINTREE_STATUS_CHANGED"
    RETRIED = "RETRIED"
    MARKED_COMPLETED = "MARKED_COMPLETED"
    ISSUED_CREDIT_NOTE = "ISSUED_CREDIT_NOTE"
    REVERSED = "REVERSED"
    NOTE_ADDED = "NOTE_ADDED"
