from __future__ import annotations

import enum


class CreditApplicationStatus(enum.StrEnum):
    SUBMITTED = "SUBMITTED"
    REVIEWER_ASSIGNED = "REVIEWER_ASSIGNED"
    REFERENCES_VERIFIED = "REFERENCES_VERIFIED"
    CREDIT_CHECK_COMPLETED = "CREDIT_CHECK_COMPLETED"
    CREDIT_CHECK_FAILED = "CREDIT_CHECK_FAILED"
    CREDIT_CHECK_INVESTIGATION_PROGRESS = "CREDIT_CHECK_INVESTIGATION_PROGRESS"
    READY_FOR_DECISION = "READY_FOR_DECISION"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    WITHDRAWN = "WITHDRAWN"
    CANCELLED = "CANCELLED"


class CreditApplicationLifecycleState(enum.StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"


class TradeReferenceVerificationStatus(enum.StrEnum):
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    DECLINED = "DECLINED"
    UNABLE_TO_VERIFY = "UNABLE_TO_VERIFY"


class OrgCreditLimitIncreaseRequestStatus(enum.StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class Industry(enum.StrEnum):
    AGRICULTURE_AND_FARMING = "AGRICULTURE_AND_FARMING"
    AUTOMOTIVE = "AUTOMOTIVE"
    CONSTRUCTION_AND_BUILDING = "CONSTRUCTION_AND_BUILDING"
    EDUCATION = "EDUCATION"
    ENERGY_AND_UTILITIES = "ENERGY_AND_UTILITIES"
    FINANCIAL_SERVICES = "FINANCIAL_SERVICES"
    FOOD_AND_BEVERAGE = "FOOD_AND_BEVERAGE"
    HEALTHCARE_AND_PHARMACEUTICALS = "HEALTHCARE_AND_PHARMACEUTICALS"
    HOME_AND_LIFESTYLE = "HOME_AND_LIFESTYLE"
    HOSPITALITY_AND_TOURISM = "HOSPITALITY_AND_TOURISM"
    IT_AND_TECHNOLOGY = "IT_AND_TECHNOLOGY"
    LOGISTICS_AND_TRANSPORT = "LOGISTICS_AND_TRANSPORT"
    MANUFACTURING = "MANUFACTURING"
    MEDIA_AND_ENTERTAINMENT = "MEDIA_AND_ENTERTAINMENT"
    PROFESSIONAL_SERVICES = "PROFESSIONAL_SERVICES"
    REAL_ESTATE = "REAL_ESTATE"
    RETAIL = "RETAIL"
    TELECOMMUNICATIONS = "TELECOMMUNICATIONS"
    WHOLESALE_AND_DISTRIBUTION = "WHOLESALE_AND_DISTRIBUTION"
    OTHER = "OTHER"


class EmployeeRange(enum.StrEnum):
    EMPLOYEES_1_10 = "1-10 employees"
    EMPLOYEES_11_50 = "11-50 employees"
    EMPLOYEES_51_200 = "51-200 employees"
    EMPLOYEES_201_500 = "201-500 employees"
    EMPLOYEES_501_1000 = "501-1000 employees"
    EMPLOYEES_1000_PLUS = "1000+ employees"


class BankAccountType(enum.StrEnum):
    BUSINESS_CURRENT = "BUSINESS_CURRENT"
    BUSINESS_SAVINGS = "BUSINESS_SAVINGS"
    OTHER = "OTHER"


class RelationshipDuration(enum.StrEnum):
    LESS_THAN_1_YEAR = "LESS_THAN_1_YEAR"
    ONE_TO_TWO_YEARS = "1_TO_2_YEARS"
    TWO_TO_FIVE_YEARS = "2_TO_5_YEARS"
    FIVE_TO_TEN_YEARS = "5_TO_10_YEARS"
    OVER_TEN_YEARS = "OVER_10_YEARS"


class ReviewFrequency(enum.StrEnum):
    MONTHLY = "MONTHLY"
    QUARTERLY = "QUARTERLY"
    ANNUALLY = "ANNUALLY"


class RejectionCategory(enum.StrEnum):
    INSUFFICIENT_REFERENCES = "INSUFFICIENT_REFERENCES"
    POOR_FINANCIAL_STANDING = "POOR_FINANCIAL_STANDING"
    INCOMPLETE_INFORMATION = "INCOMPLETE_INFORMATION"
    POLICY_NON_COMPLIANCE = "POLICY_NON_COMPLIANCE"
    OTHER = "OTHER"


class AttachmentType(enum.StrEnum):
    BANK_REFERENCE = "BANK_REFERENCE"
