import enum


class CrewEndReason(enum.StrEnum):
    EOD = "EOD"
    VEHICLE_SWAP = "VEHICLE_SWAP"
    DRIVER_HANDOVER = "DRIVER_HANDOVER"
    DRIVER_SUSPENDED = "DRIVER_SUSPENDED"
    VEHICLE_OUT_OF_SERVICE = "VEHICLE_OUT_OF_SERVICE"
    INCIDENT = "INCIDENT"
    MANUAL = "MANUAL"


class RouteCrewUnassignReason(enum.StrEnum):
    ROUTE_COMPLETED = "ROUTE_COMPLETED"
    ROUTE_CANCELLED = "ROUTE_CANCELLED"
    CREW_SWAP = "CREW_SWAP"
    DRIVER_SUSPENDED = "DRIVER_SUSPENDED"
    VEHICLE_OUT_OF_SERVICE = "VEHICLE_OUT_OF_SERVICE"
    MANUAL = "MANUAL"
